-- Tabela usuarios
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR2(255) NOT NULL,
    login VARCHAR2(255) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    perfil VARCHAR2(30) NOT NULL, 
    data_criacao DATE DEFAULT SYSDATE
    );

-- Inserir usuario
INSERT INTO usuarios
(nome_usuario, login, senha_hash, perfil)
VALUES
(:nome_usuario, :login, :senha_hash, :perfil);

-- Tabela Incidente
CREATE TABLE incidentes (
    id_incidente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_afetado VARCHAR2(100) NOT NULL,
    criticidade VARCHAR2(15) NOT NULL
        CHECK (criticidade IN ('Critico', 'Aviso', 'Informativo')),
    ativo INTEGER DEFAULT 0,
    data_modificacao DATE DEFAULT SYSDATE, 
    usuario_modificacao INTEGER,
    descricao_problema VARCHAR2(4000),
    causa_tecnica VARCHAR2(4000),
    impacto_operacional VARCHAR2(4000),
    excluido NUMBER(1) DEFAULT 0,      
    data_informativo DATE,            
    data_fim_informativo DATE,         
    CONSTRAINT fk_usuario_modificacao
        FOREIGN KEY (usuario_modificacao) REFERENCES usuarios(id_usuario)
);


-- Inserir incidente
INSERT INTO incidentes
(sistema_afetado, criticidade, ativo, data_modificacao, usuario_modificacao, descricao_problema, causa_tecnica, impacto_operacional, excluido)
VALUES 
(:sistema_afetado, :criticidade, 0, NULL, NULL, :descricao_problema, :causa_tecnica, :impacto_operacional, 0);

-- Ativar incidente
UPDATE incidentes
SET 
    ativo = 1,
    data_modificacao = SYSDATE,
    usuario_modificacao = :usuario_id
WHERE id_incidente = :id_incidente;

-- Desativar incidente
UPDATE incidentes
SET 
    ativo = 0,
    data_modificacao = SYSDATE,
    usuario_modificacao = :usuario_id
WHERE id_incidente = :id_incidente;

--Excluir incidente
UPDATE incidentes
SET 
    excluido = 1,
    data_modificacao = SYSDATE,
    usuario_modificacao = :usuario_id
WHERE id_incidente = :id_incidente;


-- Consultar incidentes ativos
SELECT 
    i.id_incidente,
    i.sistema_afetado,
    i.descricao_problema,
    i.causa_tecnica,
    i.impacto_operacional,
    i.criticidade,
    i.data_modificacao,
    i.data_informativo,
    i.data_fim_informativo,
    u.nome_usuario AS ativado_por
FROM incidentes i
LEFT JOIN usuarios u 
       ON u.id_usuario = i.usuario_modificacao 
WHERE i.ativo = 1 
  AND (i.excluido = 0 OR i.excluido IS NULL)
ORDER BY 
    CASE i.criticidade
        WHEN 'Critico' THEN 1
        WHEN 'Aviso'    THEN 2
        WHEN 'Informativo'   THEN 3
    END,
    i.data_modificacao DESC;

-- Historico de incidentes
SELECT 
    i.id_incidente,
    i.sistema_afetado,
    i.descricao_problema,
    i.causa_tecnica,
    i.impacto_operacional,
    i.criticidade,
    i.ativo,
    i.data_modificacao,
    u.nome_usuario AS ativado_por
FROM incidentes i
LEFT JOIN usuarios u 
       ON u.id_usuario = i.usuario_modificacao 
WHERE (i.excluido = 0 OR i.excluido IS NULL) 
ORDER BY i.data_modificacao DESC;